In [448]:
import numpy as np
import pandas as pd
import sklearn.tree as tree
import sklearn.linear_model as linear_model
import sklearn.preprocessing as preprocessing
import sklearn.ensemble as ensemble
import matplotlib.pyplot as plt
import sklearn.model_selection as model_selection
import sklearn.svm as svm
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier 
import warnings
warnings.filterwarnings("ignore")

In [3]:
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [399]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
# test.head()

In [8]:
drop_features = ['PassengerId', 'Survived']
train_drop = train.drop(drop_features, axis=1)
test_drop = test.drop(['PassengerId'], axis=1)

In [11]:
# train_drop
test_drop

Pclass                                          Name     Sex   Age  \
0         3                              Kelly, Mr. James    male  34.5   
1         3              Wilkes, Mrs. James (Ellen Needs)  female  47.0   
2         2                     Myles, Mr. Thomas Francis    male  62.0   
3         3                              Wirz, Mr. Albert    male  27.0   
4         3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0   
..      ...                                           ...     ...   ...   
413       3                            Spector, Mr. Woolf    male   NaN   
414       1                  Oliva y Ocana, Dona. Fermina  female  39.0   
415       3                  Saether, Mr. Simon Sivertsen    male  38.5   
416       3                           Ware, Mr. Frederick    male   NaN   
417       3                      Peter, Master. Michael J    male   NaN   

     SibSp  Parch              Ticket      Fare Cabin Embarked  
0        0      0              330911    7.8292   NaN        Q  
1        1      0              363272    7.0000   NaN        S  
2        0      0              240276    9.6875   NaN        Q  
3        0      0              315154    8.6625   NaN        S  
4        1      1             3101298   12.2875   NaN        S  
..     ...    ...                 ...       ...   ...      ...  
413      0      0           A.5. 3236    8.0500   NaN        S  
414      0      0            PC 17758  108.9000  C105        C  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0      0              359309    8.0500   NaN        S  
417      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

In [412]:
train_len = train_drop.shape[0]
titanic = pd.concat([train_drop, test_drop], axis=0, sort=False)

In [400]:
titanic

Sex  SibSp  Parch  Cabin  Family_Size  Name_Length  Pclass_1  Pclass_2  \
0      1      1      0      0          0.1     0.157143         0         0   
1      0      1      0      1          0.1     0.557143         1         0   
2      0      0      0      0          0.0     0.142857         0         0   
3      0      1      0      1          0.1     0.457143         1         0   
4      1      0      0      0          0.0     0.171429         0         0   
..   ...    ...    ...    ...          ...          ...       ...       ...   
413    1      0      0      0          0.0     0.085714         0         0   
414    0      0      0      1          0.0     0.228571         1         0   
415    1      0      0      0          0.0     0.228571         0         0   
416    1      0      0      0          0.0     0.100000         0         0   
417    1      1      1      0          0.2     0.171429         0         0   

     Pclass_3  Age_0  ...  Fare_2  Fare_3  Title_Master  Title_Miss  Title_Mr  \
0           1      0  ...       0       0             0           0         1   
1           0      0  ...       0       1             0           0         0   
2           1      0  ...       0       0             0           1         0   
3           0      0  ...       0       1             0           0         0   
4           1      0  ...       0       0             0           0         1   
..        ...    ...  ...     ...     ...           ...         ...       ...   
413         1      0  ...       0       0             0           0         1   
414         0      0  ...       0       1             0           0         0   
415         1      0  ...       0       0             0           0         1   
416         1      0  ...       0       0             0           0         1   
417         1      1  ...       1       0             1           0         0   

     Title_Mrs  Title_Rare  Embarked_C  Embarked_Q  Embarked_S  
0            0           0           0           0           1  
1            1           0           1           0           0  
2            0           0           0           0           1  
3            1           0           0           0           1  
4            0           0           0           0           1  
..         ...         ...         ...         ...         ...  
413          0           0           0           0           1  
414          0           1           1           0           0  
415          0           0           0           0           1  
416          0           0           0           0           1  
417          0           0           1           0           0  

[1309 rows x 27 columns]

In [375]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 27 columns):
Sex             1309 non-null int64
SibSp           1309 non-null int64
Parch           1309 non-null int64
Cabin           1309 non-null int64
Name_Length     1309 non-null float64
Pclass_1        1309 non-null uint8
Pclass_2        1309 non-null uint8
Pclass_3        1309 non-null uint8
Age_0           1309 non-null uint8
Age_1           1309 non-null uint8
Age_2           1309 non-null uint8
Age_3           1309 non-null uint8
Age_4           1309 non-null uint8
Age_5           1309 non-null uint8
Fare_0          1309 non-null uint8
Fare_1          1309 non-null uint8
Fare_2          1309 non-null uint8
Fare_3          1309 non-null uint8
Title_Master    1309 non-null uint8
Title_Miss      1309 non-null uint8
Title_Mr        1309 non-null uint8
Title_Mrs       1309 non-null uint8
Title_Rare      1309 non-null uint8
Embarked_C      1309 non-null uint8
Embarked_Q      1309 non-nul

In [413]:
titanic['Title'] = titanic.Name.apply(lambda name: name.split(',')[1].split('.')[0].strip())

In [162]:
titanic.Title.value_counts()

Mr              757
Miss            260
Mrs             197
Master           61
Rev               8
Dr                8
Col               4
Major             2
Mlle              2
Ms                2
Dona              1
Jonkheer          1
Capt              1
the Countess      1
Mme               1
Lady              1
Don               1
Sir               1
Name: Title, dtype: int64

In [414]:
rare_title = titanic.Title.value_counts().index[4:].tolist()
mapping={}
for s in rare_title:
    mapping[s]='Rare'
titanic['Title'] = titanic['Title'].map(lambda x: mapping[x] if x in mapping else x)

In [415]:
grouped = titanic.groupby(['Title'])
grouped.groups

{'Master': Int64Index([  7,  16,  50,  59,  63,  65,  78, 125, 159, 164, 165, 171, 176,
             182, 183, 193, 261, 278, 305, 340, 348, 386, 407, 445, 480, 489,
             549, 709, 751, 755, 787, 788, 802, 803, 819, 824, 827, 831, 850,
             869,  21,  55,  64,  80,  89, 154, 161, 192, 194, 196, 201, 244,
             281, 307, 339, 344, 360, 379, 389, 392, 417],
            dtype='int64'),
 'Miss': Int64Index([  2,  10,  11,  14,  22,  24,  28,  32,  38,  39,
             ...
             371, 375, 376, 385, 400, 402, 408, 409, 410, 412],
            dtype='int64', length=260),
 'Mr': Int64Index([  0,   4,   5,   6,  12,  13,  17,  20,  21,  23,
             ...
             399, 401, 403, 404, 405, 406, 407, 413, 415, 416],
            dtype='int64', length=757),
 'Mrs': Int64Index([  1,   3,   8,   9,  15,  18,  19,  25,  31,  40,
             ...
             364, 365, 368, 374, 382, 383, 391, 395, 397, 411],
            dtype='int64', length=197),
 'Rare': Int64Inde

In [416]:
median = grouped.Age.median()
median

Title
Master     4.0
Miss      22.0
Mr        29.0
Mrs       35.5
Rare      44.5
Name: Age, dtype: float64

In [99]:
grouped.Age.mean()

Title
Master     5.482642
Miss      21.774238
Mr        32.252151
Mrs       36.994118
Rare      42.656250
Name: Age, dtype: float64

In [417]:
# set default age 
def set_default_age(cols):
    age = cols[0]
    title = cols[1]
    if pd.isnull(age):
        return median[title]
    return age

titanic.Age = titanic[['Age', 'Title']].apply(set_default_age, axis=1)

In [418]:
# Age 离散化
titanic.Age = pd.cut(titanic.Age, 5, labels=False)

In [419]:
titanic.Fare.fillna(titanic.Fare.median(), inplace=True)

In [420]:
# Fare 离散化 
titanic.Fare = pd.qcut(titanic.Fare, 4, labels=False)

In [421]:
# 添加 Family_Size
titanic['Family_Size'] = titanic['SibSp'] + titanic['Parch'] + 1
titanic['Name_Length'] = titanic['Name'].apply(lambda x: len(x))

In [422]:
# Cabin 映射
titanic['Cabin'] = titanic['Cabin'].apply(lambda x: 0 if pd.isna(x) else 1)

In [481]:
titanic.head()

Sex  Cabin  Family_Size  Name_Length  Pclass_1  Pclass_2  Pclass_3  \
0    1      0          0.1     0.157143         0         0         1   
1    0      1          0.1     0.557143         1         0         0   
2    0      0          0.0     0.142857         0         0         1   
3    0      1          0.1     0.457143         1         0         0   
4    1      0          0.0     0.171429         0         0         1   

   SibSp_0  SibSp_1  SibSp_2  ...  Fare_2  Fare_3  Title_Master  Title_Miss  \
0        0        1        0  ...       0       0             0           0   
1        0        1        0  ...       0       1             0           0   
2        1        0        0  ...       0       0             0           1   
3        0        1        0  ...       0       1             0           0   
4        1        0        0  ...       0       0             0           0   

   Title_Mr  Title_Mrs  Title_Rare  Embarked_C  Embarked_Q  Embarked_S  
0         1          0           0           0           0           1  
1         0          1           0           1           0           0  
2         0          0           0           0           0           1  
3         0          1           0           0           0           1  
4         1          0           0           0           0           1  

[5 rows x 40 columns]

In [424]:
Pclass_dummy = pd.get_dummies(titanic.Pclass, prefix='Pclass')
Age_dummy = pd.get_dummies(titanic.Age, prefix='Age')
Fare_dummy = pd.get_dummies(titanic.Fare, prefix='Fare')
Title_dummy = pd.get_dummies(titanic.Title, prefix='Title')
Embarked_dummy = pd.get_dummies(titanic.Embarked, prefix='Embarked')

In [425]:
SibSp_dummy = pd.get_dummies(titanic.SibSp, prefix='SibSp')
Parch_dummy = pd.get_dummies(titanic.Parch, prefix='Parch')

In [426]:
titanic = pd.concat([titanic, Pclass_dummy, SibSp_dummy, Parch_dummy, Age_dummy, Fare_dummy, Title_dummy, Embarked_dummy], axis=1, sort=False)

In [427]:
# titanic.drop(['Name', 'Pclass', 'Age', 'Title', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
# titanic.drop(['Name', 'Pclass', 'Age', 'Title', 'Ticket', 'Fare', 'Embarked'], axis=1, inplace=True)
titanic.drop(['Name', 'Pclass', 'SibSp', 'Parch', 'Age', 'Title', 'Ticket', 'Fare', 'Embarked'], axis=1, inplace=True)

In [428]:
titanic.Sex = titanic.Sex.map({'male':1,'female':0})

In [429]:
# Name_Length 归一化 
minMax_scaler = preprocessing.MinMaxScaler()
titanic['Name_Length'] = minMax_scaler.fit_transform(np.array(titanic['Name_Length']).reshape(-1, 1))
titanic['Family_Size'] = minMax_scaler.fit_transform(np.array(titanic['Family_Size']).reshape(-1, 1))

In [431]:
x_train = titanic[:train_len]
y_train = train['Survived']
x_test = titanic[train_len:]

In [480]:
# SVM
# svc = svm.LinearSVC()
svc = svm.SVC(C=8)
model_selection.cross_val_score(svc, x_train, y_train, cv=5)

array([0.84357542, 0.82681564, 0.82022472, 0.78651685, 0.86440678])

In [ ]:
array([0.86592179, 0.82681564, 0.82022472, 0.79775281, 0.86440678])  # C=4 
array([0.8603352 , 0.82681564, 0.82022472, 0.80337079, 0.87570621])  # C=6.2
array([0.8603352 , 0.82681564, 0.82022472, 0.80337079, 0.8700565 ])  # C=6
array([0.84916201, 0.82681564, 0.82022472, 0.79775281, 0.85310734])
array([0.8547486 , 0.79888268, 0.79775281, 0.79213483, 0.85875706])
array([0.83240223, 0.81564246, 0.80337079, 0.78651685, 0.85310734])
array([0.83798883, 0.81005587, 0.81460674, 0.79213483, 0.86440678])

In [482]:
svc.fit(x_train, y_train)
predict_svc = svc.predict(x_test)
predict_svc

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [472]:
# knn
knn = KNeighborsClassifier(n_neighbors = 10)
model_selection.cross_val_score(knn, x_train, y_train, cv=5)

array([0.79888268, 0.81005587, 0.8258427 , 0.78651685, 0.85310734])

In [474]:
knn.fit(x_train, y_train)
predict_knn = knn.predict(x_test)
predict_knn

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [464]:
decision_tree = tree.DecisionTreeClassifier(min_samples_leaf=4)
model_selection.cross_val_score(decision_tree, x_train, y_train, cv=5)

array([0.77094972, 0.79888268, 0.83707865, 0.78089888, 0.77966102])

In [475]:
# LogisticRegression
lr = linear_model.LogisticRegression()
model_selection.cross_val_score(lr, x_train, y_train, cv=5)

array([0.83798883, 0.80446927, 0.79775281, 0.80337079, 0.86440678])

In [ ]:
# array([0.84916201, 0.81005587, 0.80337079, 0.80898876, 0.85875706])
# array([0.83798883, 0.81005587, 0.80337079, 0.79213483, 0.85310734])
# array([0.83240223, 0.79888268, 0.79775281, 0.79213483, 0.83615819])

In [476]:
lr.fit(x_train, y_train)
predict_lr = lr.predict(x_test)
predict_lr

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [494]:
# xgboost
gbm = XGBClassifier( n_estimators= 2000, max_depth= 4, min_child_weight= 2, gamma=0.9, subsample=0.8, 
                     colsample_bytree=0.8, objective= 'binary:logistic', nthread= -1, scale_pos_weight=1)
model_selection.cross_val_score(gbm, x_train, y_train, cv=5)

array([0.79329609, 0.82681564, 0.83146067, 0.82022472, 0.83050847])

In [ ]:
array([0.7877095 , 0.82681564, 0.8258427 , 0.8258427 , 0.81920904])

In [495]:
gbm.fit(x_train, y_train)
predict_gbm = gbm.predict(x_test)
predict_gbm

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [ ]:
array([0.7877095 , 0.7877095 , 0.87078652, 0.81460674, 0.85310734])  # xgboost
array([0.83798883, 0.81005587, 0.81460674, 0.79213483, 0.86440678])  # svc 
array([0.83240223, 0.81005587, 0.80337079, 0.78651685, 0.84180791])  # 加上 Embarked 
array([0.83240223, 0.81005587, 0.80337079, 0.79213483, 0.83615819])

In [505]:
adaboost_clf = ensemble.AdaBoostClassifier(n_estimators=100, learning_rate=0.1)
model_selection.cross_val_score(adaboost_clf, x_train, y_train, cv=5)

array([0.83240223, 0.82122905, 0.81460674, 0.82022472, 0.83615819])

In [506]:
adaboost_clf.fit(x_train, y_train)
predict_ada = adaboost_clf.predict(x_test)
predict_ada

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [520]:
# 模型融合
predict = 0.3*predict_svc + 0.11*predict_lr + 0.08*predict_knn + 0.11*predict_gbm + 0.4*predict_ada
predict

array([0.  , 0.7 , 0.  , 0.  , 0.81, 0.  , 0.81, 0.  , 1.  , 0.  , 0.  ,
       0.08, 1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.81, 1.  , 0.08, 1.  ,
       1.  , 0.11, 1.  , 0.  , 1.  , 0.  , 0.  , 0.11, 0.  , 0.  , 0.89,
       1.  , 0.22, 0.11, 0.81, 0.81, 0.  , 0.11, 0.  , 0.19, 0.  , 1.  ,
       1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.92, 1.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  ,
       1.  , 0.  , 0.3 , 1.  , 1.  , 0.  , 0.81, 0.3 , 1.  , 0.22, 0.  ,
       1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.81, 0.81,
       0.78, 1.  , 0.81, 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.89,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.92, 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 1.  , 1.  , 1.  , 1.  , 0.11, 0.  , 1.  , 0.22, 1.  , 1.  ,
       0.  , 1.  , 0.  , 0.  , 0.81, 0.  , 1.  , 0.  , 0.  , 0.  , 0.51,
       0.  , 0.  , 0.  , 0.  , 0.11, 0.  , 0.81, 0.  , 0.  , 1.  , 0.  ,
       0.  , 0.19, 0.  , 0.11, 0.  , 0.08, 0.  , 1.

In [521]:
for i in range(len(predict)):
    if predict[i] >= 0.5:
        predict[i] = 1
    else:
        predict[i] = 0

predict = predict.astype(np.int64)
print(len(predict))
predict

418


array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [522]:
predict.dtype

dtype('int64')

In [224]:
# 模型融合
clf = linear_model.LogisticRegression(C=1.0, penalty='l2', tol=1e-6)
bagging_clf = ensemble.BaggingRegressor(clf, n_estimators=20, max_samples=0.9, max_features=0.88, bootstrap=True, bootstrap_features=False)
model_selection.cross_val_score(bagging_clf, x_train, y_train, cv=5)

array([0.29904308, 0.38049354, 0.28259208, 0.18958923, 0.46563147])

In [205]:
# help(model_selection.cross_val_score)
len(predict)

418

In [523]:
submission = pd.DataFrame({'PassengerId':test['PassengerId'], 'Survived':predict})
submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [524]:
submission.to_csv('./submission.csv', index=False)